name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  # Service Principal with Certificate Example
  service_principal_with_certificate:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/service_principal_with_certificate/'
  
  # Service Principal with Password Example
  service_principal_with_password:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/service_principal_with_password/'
  
  # Separate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
